# Generated by Django 5.0.3 on 2024-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pick',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
    ]
